site_name: My Docs
theme:
  name: material
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [ . ]
          options:
            members_order: source
            separate_signature: true
            filters: [ "!^_" ]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
          import:
            - url: https://docs.python.org/3/objects.inv
              domains: [ py, std ]
